name: Automated tests part 1

on: [push, pull_request]

jobs:
  ex1:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        deno: ["v1.6.3"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup deno ${{matrix.deno}}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}

      - name: Setup MongoDB ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Run program
        run: deno run -A ./.github/.tests/part2/ex1ToDo.ts > ./tmp

      - name: Run test
        run: deno run -A ./.github/.tests/part2/ex1.ts ./tmp

  ex2:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        deno: ["v1.6.3"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup deno ${{matrix.deno}}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}

      - name: Setup MongoDB ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Run program
        run: deno run -A ./.github/.tests/part2/ex2ToDo.ts > ./tmp

      - name: Run test
        run: deno run -A ./.github/.tests/part2/ex2.ts ./tmp

  ex3:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        deno: ["v1.6.3"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup deno ${{matrix.deno}}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}

      - name: Setup MongoDB ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Run program
        run: deno run -A ./.github/.tests/part2/ex3ToDo.ts > ./tmp

      - name: Run test
        run: deno run -A ./.github/.tests/part2/ex3.ts ./tmp

  ex4:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        deno: ["v1.6.3"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup deno ${{matrix.deno}}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}

      - name: Setup MongoDB ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Run program
        run: deno run -A ./.github/.tests/part2/ex4ToDo.ts > ./tmp

      - name: Run test
        run: deno run -A ./.github/.tests/part2/ex4.ts ./tmp

  ex5:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        deno: ["v1.6.3"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup deno ${{matrix.deno}}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}

      - name: Setup MongoDB ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Run program
        run: deno run -A ./.github/.tests/part2/ex5ToDo.ts > ./tmp

      - name: Run test
        run: deno run -A ./.github/.tests/part2/ex5.ts ./tmp

  ex6:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        deno: ["v1.6.3"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup deno ${{matrix.deno}}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}

      - name: Setup MongoDB ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Run program
        run: deno run -A ./.github/.tests/part2/ex6ToDo.ts > ./tmp

      - name: Run test
        run: deno run -A ./.github/.tests/part2/ex6.ts ./tmp